server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Necesario para aplicaciones SPA (React Router) para evitar error 404 al recargar páginas
        try_files $uri $uri/ /index.html;
    }
}
